spring:
  redis:
    sentinel:
      master: mymaster  #指定master名称
      nodes:  #指定sentinel节点的集群信息
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381
    #    host: localhost
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 1000
